# Generated by Django 5.0.3 on 2024-03-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("rg", models.CharField(max_length=30)),
                ("cpf", models.CharField(max_length=30)),
                ("data_nascimento", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("B", "Básico"),
                            ("I", "Intermediário"),
                            ("A", "Avançado"),
                        ],
                        max_length=2,
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
            ],
        ),
    ]
