# Generated by Django 5.0.3 on 2024-03-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_escola", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="nivel",
            field=models.CharField(
                choices=[("B", "Básico"), ("I", "Intermediário"), ("A", "Avançado")],
                default="B",
                max_length=2,
            ),
        ),
    ]
