# Generated by Django 5.0.3 on 2024-03-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_escola", "0002_alter_curso_nivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="cpf",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="rg",
            field=models.CharField(max_length=9),
        ),
    ]
