# Generated by Django 5.0.3 on 2024-03-10 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_escola", "0003_alter_aluno_cpf_alter_aluno_rg"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matricula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("V", "Vespertino"),
                            ("M", "Matutino"),
                            ("N", "Noturno"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_escola.aluno",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_escola.curso",
                    ),
                ),
            ],
        ),
    ]
